/**
 * SEO 게시판 시드 빌더
 *   사용법: node seo-seed/build.mjs seo-seed/batch-01.js > seo-seed/out/batch-01.sql
 *
 * 각 배치 파일은 default export 로 글 객체 배열을 내보낸다:
 *   { category, slug, title, excerpt, content(HTML), tags[], faq[{q,a}] }
 *
 * - INSERT OR IGNORE → (category, slug) UNIQUE 제약으로 재실행 시 중복 방지
 * - 작은따옴표는 '' 로 escape (SQLite 표준)
 */
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';

const sq = (v) => `'${String(v == null ? '' : v).replace(/'/g, "''")}'`;

function rowSql(p) {
  if (!p.category || !p.slug || !p.title || !p.content) {
    throw new Error(`필수 필드 누락: ${JSON.stringify({ category: p.category, slug: p.slug })}`);
  }
  if (!/^[a-z0-9-]{2,80}$/.test(p.slug)) {
    throw new Error(`slug 형식 오류(a-z,0-9,-): ${p.slug}`);
  }
  const tags = JSON.stringify(Array.isArray(p.tags) ? p.tags : []);
  const faq  = JSON.stringify(Array.isArray(p.faq) ? p.faq : []);
  const author = p.author || 'InsureConnect 편집팀';
  const cols = '(category, slug, title, excerpt, content, tags, faq_json, status, author)';
  const vals = [
    sq(p.category), sq(p.slug), sq(p.title), sq(p.excerpt || ''),
    sq(p.content), sq(tags), sq(faq), sq(p.status || 'published'), sq(author),
  ].join(', ');
  return `INSERT OR IGNORE INTO ic_seo_posts ${cols} VALUES (${vals});`;
}

const file = process.argv[2];
if (!file) { console.error('Usage: node build.mjs <batch-file.js>'); process.exit(1); }

const mod = await import(pathToFileURL(resolve(file)).href);
const posts = mod.default;
if (!Array.isArray(posts)) { console.error('batch default export must be an array'); process.exit(1); }

// slug 중복 검사
const seen = new Set();
for (const p of posts) {
  const key = `${p.category}/${p.slug}`;
  if (seen.has(key)) throw new Error(`배치 내 slug 중복: ${key}`);
  seen.add(key);
}

const out = ['-- auto-generated by seo-seed/build.mjs', `-- posts: ${posts.length}`, ...posts.map(rowSql)];
console.log(out.join('\n'));
console.error(`✓ ${posts.length}개 글 SQL 생성 완료`);
